[package]
name = "lab02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "bomb"
path = "src/bomb/bomb.rs"

[[bin]]
name = "adventure_game"
path = "src/adventure/adventure_game.rs"

[dependencies]
